version: '2'
services:
    hhcfronth2-app:
        image: hhcfronth2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hhcfronth2-postgresql:5432/HHCFrontH2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hhcfronth2-elasticsearch:9300
        ports:
            - 8080:8080
    hhcfronth2-postgresql:
        extends:
            file: postgresql.yml
            service: hhcfronth2-postgresql
    hhcfronth2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hhcfronth2-elasticsearch
